#!/bin/bash
set -e

echo Setup Helmet for MRBuggy3 SITL
pushd ~/cognipilot
if [ ! -d helmet ] ; then
  git clone git@github.com:CogniPilot/helmet
fi
vcs import < helmet/dream/base.yaml
vcs import < helmet/dream/mrbuggy3.yaml
popd

echo Build Cranium
pushd ~/cognipilot/cranium
colcon build --symlink-install
. ./install/setup.sh
popd

echo Build Cerebri for MRBuggy3 SITL
pushd ~/cognipilot/ws/cerebri
if [ ! -d ~/cognipilot/ws/.west ] ; then
  west init -l .
fi
west update
west build app/mrbuggy3/ -b native_posix -t install -p
. ./install/setup.sh
popd

echo Build Cyecca
pushd ~/cognipilot/tools/src/cyecca
poetry install
popd

echo Build Electrode
pushd ~/cognipilot/electrode
colcon build --symlink-install
. ./install/setup.sh
popd
