#!/bin/bash
set -e

echo Setup Helmet for b3rb SIL
pushd ~/cognipilot
if [ ! -d helmet ] ; then
  git clone git@github.com:CogniPilot/helmet
fi
vcs import < helmet/dream/base.yaml
vcs import < helmet/dream/b3rb.yaml
popd

echo Build Cranium
pushd ~/cognipilot/cranium
colcon build --symlink-install
. ./install/setup.sh
popd

echo Build Cerebri for b3rb SIL
pushd ~/cognipilot/ws/cerebri
if [ ! -d ~/cognipilot/ws/.west ] ; then
  west init -l .
fi
west update
west build app/b3rb/ -b native_sim -t install -p
. ./install/setup.sh
popd

echo Build Cyecca
pushd ~/cognipilot/tools/src/cyecca
poetry install
popd

echo Build Electrode
pushd ~/cognipilot/electrode
colcon build --symlink-install
. ./install/setup.sh
popd
