#!/bin/bash
set -e

# setup cyecca poetry env for use by ros (using shebang)
mkdir -p ~/bin
cat << EOF >> ~/bin/python_cyecca
#!/bin/bash
poetry run -C ~/work/cyecca python \$@
EOF
chmod +x ~/bin/python_cyecca

poetry install -C ~/work/cyecca
poetry run -C ~/work/cyecca jupyter lab
