#!/bin/bash
set -e

curl -sSL https://install.python-poetry.org | sudo POETRY_HOME=/opt/poetry python3 -

# setup cyecca poetry env for use by ros (using shebang)
mkdir -p ~/bin
cat << EOF >> ~/bin/python_cyecca
#!/bin/bash
pushd ~/cognipilot/tools/src/cyecca
poetry run python \$@
popd
EOF
chmod +x ~/bin/python_cyecca

pushd ~/cognipilot/tools/src/cyecca
poetry install
poetry run jupyter lab
popd
