#!/bin/bash
set -e

# setup cyecca poetry env for use by ros (using shebang)
mkdir -p ~/bin
cat << EOF >> ~/bin/python_cyecca
#!/bin/bash
poetry run -C ~/cognipilot/tools/src/cyecca python \$@
EOF
chmod +x ~/bin/python_cyecca

poetry install -C ~/cognipilot/tools/src/cyecca
poetry run -C ~/cognipilot/tools/src/cyecca jupyter lab
