#!/bin/bash
set -e
echo Build CogniPilot Docs
cd ~/cognipilot
if [ ! -d ~/cognipilot/docs ] ; then
  git clone git@github.com:CogniPilot/cognipilot_docs ~/cognipilot/docs
fi
cd ~/cognipilot/docs
poetry install --no-root
poetry run mkdocs serve -a 0.0.0.0:8000
